### ISSUE TITLE
Custom "configure" command not fully functional

### ISSUE THREAD

**Issue by vpelletier** [hexagonit/hexagonit.recipe.cmmi#2]
When providing a custom "configure" command has the following short-commings:
- build directory is not detected as such
- --prefix parameter is not provided

I have patches for those 3 problems, and another improving a big the error message involved (I include path searched in, so one can check if his config is correctly taken into account).

Please tell me how I should contribute those patches, and how you can review them (if desired).

**Comment by vpelletier** [comment]
Fixes commited on lukenowak/hexagonit.recipe.cmmi branch:
lukenowak/hexagonit.recipe.cmmi/commit/b569fb6e0e04f041357c7d837f661bac19629aaf
lukenowak/hexagonit.recipe.cmmi/commit/fc4180fad645fa820cf7762f05de4cb2d6062b60
lukenowak/hexagonit.recipe.cmmi/commit/44ec6376762829074d4b6e6de2817667d451917f

**Comment by hexagonit** [comment]
I agree that the build directory detection benefits from taking into account the custom configure command.

As for the --prefix parameter issues, it feels more a documentation issue. I always considered the automatic --prefix a special case and the reason for it was to make the recipe compatible with zc.recipe.cmmi. You can always provide a --prefix in the `configure-options` option and I would prefer this over introducing a new option (`configure-needs-prefix`). We could make this explicit in the documentation saying that if you use `configure-command` to override the default than --prefix won't be automatically added.

No objections on improving the error reporting.

cheers,
Kai

**Comment by vpelletier** [comment]
For build directory detection & error reporting, feel free to cherry-pick my commits from lukenowak's tree.

For --prefix, I understand. Thing is, I'm very new to buildout configuration, so I didn't know (and still only have a rather vague idea) how to "compute" --prefix's value from configuration file, so I put the complexity in python code. No problem with dropping the configure-needs-prefix idea and guessing it from configure-command presence (although it's a bit less orthogonal... not a huge deal).

**Comment by hexagonit** [comment]
I took a closer look now and your suggested fix for doing the build dir detection using the configure_cmd does not work. The configure_cmd may be something like

```
configure-command = perl -I${buildout:perl_lib}/lib/perl5 Makefile.PL INSTALL_BASE=${buildout:perl_lib}
```

so calling `os.path.isfile(configure_cmd)` will fail. The detection needs to based on a file that is contained within the package that was extracted. As you can see from the code the main reason for having this is to support packages that either extract to the $PWD or extract under a $PWD/some_directory and them be able to detect whether the package contained something the user expected (mainly the configure script).

So either we would need to introduce an option for defining the name of the file (e.g. "configure", "Makefile.PL", "some-custom-script") that we are expecting to find or we could alternatively just omit the check and attempt building. If the package does not contain the files required for the build then the recipe would fail. In the latter case the error report would be worse though. However, if you use the md5sum option to verify the package then you could be fairly certain that it always contains the needed files. I would favor the latter option of omitting the explicit test for a particular file. What do you think?

**Comment by hexagonit** [comment]
I came across an issue with the `is_build_dir()` heuristic myself while building HAProxy with hexagonit.recipe.cmmi and decided that it is better to get rid of to accommodate many different kinds of packages that can be otherwise built with the recipe.

I just pushed to commits to github and I will release a 1.4.0 version soon. Could you try the latest version and see if it takes care of your use cases? I can still apply patches before releasing if anything comes up.

cheers,
Kai
